Create apps/box86/uninstall.sh

diff --git a/apps/box86/uninstall b/apps/box86/uninstall
--- a/apps/box86/uninstall
+++ b/apps/box86/uninstall
@@ -10,8 +10,14 @@ function uninstall-compiled() {
 if [[ "$STATUS" == "compiled" ]]; then
     uninstall-compiled
 elif [[ "$STATUS" == "installed" ]]; then
-    #Uninstallation commands
-    echo "not implemented yet"
+    echo "uninstalling box86..."
+    sudo apt purge box86 -y || error "Failed to uninstall box86!"
+    echo "removing box86 repo..."
+    sudo rm -f /etc/apt/sources.list.d/box86.list || error "Failed to remove repo!"
+    echo "removing box86 repo key..."
+    sudo apt-key remove "5DBC E818 72C0 609D 3C47  61AA EB3C E9A3 37EC DFA4" || error "Failed to remove key!"
+    echo "running 'sudo apt update'..."
+    sudo apt update
 else
     echo "box86 isn't installed" | yad --text-info --button=Cancel
     exit 0
